@startuml
abstract class AbstractEnemyFactory{
    + {abstract} create():AbstractEnemy
}
class MobEnemyFactory{
    + create():MobEnemy
}
class EliteEnemyFactory{
    + create():EliteEnemy
}
class BossEnemyFactory{
    + create():BossEnemy
}

AbstractEnemyFactory <|-- MobEnemyFactory
AbstractEnemyFactory <|-- EliteEnemyFactory
AbstractEnemyFactory <|-- BossEnemyFactory

abstract class AbstractEnemy {
    + AbstractEnemy(int locationX, int locationY, int speedX, int speedY)
    + forward():void
}

class MobEnemy {
    + MobEnemy(int locationX, int locationY, int speedX, int speedY)
    + shoot():List<BaseBullet>
}

class EliteEnemy {
    - direction:int
    - power:int
    + EliteEnemy(int locationX, int locationY, int speedX, int speedY)
    + shoot():List<BaseBullet>
}

class BossEnemy {
    + EliteEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + shoot():List<BaseBullet>
}

AbstractEnemy <|-- MobEnemy
AbstractEnemy <|-- EliteEnemy
AbstractEnemy <|-- BossEnemy
MobEnemyFactory ..> MobEnemy : <<create>>
EliteEnemyFactory ..> EliteEnemy : <<create>>
BossEnemyFactory ..> BossEnemy : <<create>>

class Game {
    - enemyAircrafts:List<AbstractEnemy>
    - enemyFactories:List<AbstractEnemyFactory>
    + action():void
}

Game --> AbstractEnemyFactory
Game --> AbstractEnemy
@enduml