@startuml
class HeroAircraft {
    - shootNum:int
    - power:int
    - direction:int
    - {static} instance:HeroAircraft
    - HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + {static} getInstance():HeroAircraft
    + forward():void
    + shoot():List<BaseBullet>
}
class Game {
    - heroAircraft:HeroAircraft
    + action():void
}
HeroAircraft <-- Game
HeroAircraft <-- HeroAircraft
@enduml